#+TITLE: Colombia Tribal

A story game in the tribal epoch of Colombia.

* Project

** Game engine

The Game story and actions are specified in ORG files. These contain
all the story and define possible actions so that the player can
navigate from one dialogue to another.

The package =DYNAMIC-TEXT-BOOK= contains the necessary tools to compile
the ORG file into Lisp code. The compilation creates a new package and
two hash-tables:
 - =|*stories*|= A Story contains some text as well as actions for the
   player to choose from,
 - =|*actions*|= An action is a text that you want the player to read
   as a transition between two stories.

The package =GAME= uses =DYNAMIC-TEXT-BOOK:BUILD-BOOK= in order to
compile the game defined by the file [[file:src/resources/story/start.org][start.org]].

* Development log

** Story line and actions

We will be one software dev and a politician student developing this
game, one of us is clearly not going to learn how to manage with lisp
conses even for writing configuration files. Thus I think that using
ORG files to write all the story logic is a better idea. It will still
need some rigor from the non-devs but is going to be ok with a bit of
my help.

These ORG files will need some syntax in order to be interpreted by
the game text engine.

** Javascript

The game will firstly use static HTML pages with links to other pages.

We could as a bonus implement an optional javascript feature that
would make the game nicer to play on a remote web-server. The
javascript option must not be necessary to play the game so that
everyone can play it!
