# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: davd33290/cl-roswell:1.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      GAME: colombia-tribal

    steps:
      - checkout

      - run: cd src/
      - run: ros build ../colombia-tribal.ros
      - run: scp ../colombia-tribal root@172.105.86.13:/root/colombia-tribal/colombia-tribal.exe~
