* STORY Intro

Deep into the wilderness of south America, where human kind live in
compassion with nature and the old ways are still remembered.  At the
north of Colombia, there is a special mount named Sierra Nevada de
Santa Marta.  At the south of this mount, there is a place that people
call Guatapuri where it is believed that an elder indigenous community
of humans lived: the Koguis.

Their beliefs were closely linked with nature. At the center of the
universe, the Mamas (sun power, male shamans) and the Sagas (moon
power, female shamans) took care of the spiritual and social order of
the community. The chosen children used to go through a formation from
birth during 18 years in the Gonawindua mountain, the heart of the
world, where they would develop a deep consciousness of natural
phenomena. After this magical experience they become the guardians of
the universe equilibrium.

** ACTIONS
"Be a sun child", The Opening
** IMAGE the-mount.jpg
* STORY The Opening

As a Sun Children, you have gone through a lot of ceremonies.
Now you can communicate with nature.

Mamu is your spiritual guide, he supports you as you learn all the
ways of the shamans.

In the cavern, where you are, you can hear noises near the current of
water on the east. You also see different colors on the walls. And
remember Mamu explaining how they are the veins of the moutain.

** ACTIONS
Walk To The River, The River
** IMAGE the-mount.jpg
* STORY The River

You are now stepping on the cold water and feel totally safe.

You look down, touch the water. Lights are coming out of your hands. It's warm.

The river says: "You're touching my chest! I'm the spirit of water. I am
here to clean and make the green grow.  First, there was the sea. All
was dark. There was neither Sun nor Moon nor people, no plants or
animals. The sea was everywhere, the water was the mother. She was the
spirit of what was to come and she was thought and memory."
** ACTIONS
Pray to The Water Spirit, Pray the water spirit
"Come back to the beginning", The Opening
** IMAGE the-mount.jpg
* STORY The Old Market

You arrive at a beautiful space in-between the trees that seem to be
enchanted by the magics of the Pachamama, you feel fulfilled again.

* STORY Pray the water spirit

The spirit says: "I can be life, I can be death. I am limitless."

** ACTIONS
"Go back to the Cavern entrance.", Walk back to the cavern
** IMAGE pray-the-water-spirit.jpg
* STORY Walk back to the cavern

Arriving back at the center of the cavern, you suddenly hear a heart beating faster and faster.
It appears to come from the deep inners of the moutain.
** ACTIONS
"Kneel to listen the ground", Listen the ground
** IMAGE the-cavern.jpg
* STORY Listen the ground

You kneel on the ground, put your hands on it and feel them
burning. You then settle your head to listen the earth. You listen carefully:
you hear her screaming!

"THEY ARRE DESTROYINNG ME.... It is PAAINFUL!"
She cries.
** IMAGE listen-the-ground.jpg
* ACTION Walk To The River

You feel attracted by the river and slowly walk towards it.
** IMAGE the-mount.jpg
* ACTION Pray to The Water Spirit

You kneel down, placing your face in the river's cold water.
** IMAGE pray-the-water-spirit.jpg
